server {
    listen 0.0.0.0 8080;

    location / {
        root html;

        # No index file means we'll get a directory index when navigating to the root of the website
        autoindex on off;
    }

    location /images {
        root html/resources;

        autoindex on;
    }
}
