server {
    listen 0.0.0.0 8080;

    location / {
        root html;
    }
}

server {
    # Even if the interface is different, the port is already taken by the first
    # server directive (since it's a 0.0.0.0 listen, so on all interfaces)
    listen 127.0.0.1 8080;

    location /images {
        root html/resources/images;
    }
}
