server {
    listen 0.0.0.0 8080;

    location / {
        root html;
    }
}

server {
    # Duplicate ports aren't accepted because we don't support virtual hosts
    listen 0.0.0.0 8080;

    location /images {
        root html/resources/images;
    }
}
