server {
    listen 0.0.0.0 80;

    location /images {
        root html/resources;

        # To be able to see our changes
        autoindex on;

        # Defines the folder in which uploaded files will be put
        upload_store;
    }
}
