server {
    listen 0.0.0.0 8080;

    location / {
        root html;

        # No index file means we'll get a directory index when navigating to the root of the website
        autoindex on;
    }

    location /images {
        root html/resources;

        # This means we'll get an index page if we navigate to /images, but any subdirectory
        # there will get a directory listing (like going to /images/)
        index index.html;

        autoindex on;
    }
}
