server {
    # Listen is necessary to know which port to open, and on which interface
    # This makes it listen on all interfaces
    listen 0.0.0.0 8080;

    location / {
        allowed_methods GET;

        root html;
    }
}
