server {
    listen 0.0.0.0 8080;

    location / {
        allowed_methods GET;

        root html;
    }

    # Redirect all requests to /this/is/root to the / root location
    location /this/is/root/ {
        allowed_methods GET;

        redirect 301 /;
    }
}
