server {
    listen 0.0.0.0 8080;

    location / {
        allowed_methods GET;

        root html;
    }
}

server {
    listen 0.0.0.0 10443;

    location / {
        allowed_methods GET;

        root html;
    }
}
